---
apiVersion: v1
kind: Namespace
metadata:
  name: spotifilter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotifilter
  namespace: spotifilter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spotifilter
  template:
    metadata:
      labels:
        app: spotifilter
    spec:
      containers:
        - name: spotifilter
          env:
            - name: TELEGRAM_USERNAME
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_USERNAME
                  name: spotifilter
            - name: SPOTIPY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: SPOTIPY_CLIENT_ID
                  name: spotifilter
            - name: SPOTIPY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: SPOTIPY_CLIENT_SECRET
                  name: spotifilter
            - name: GENIUS_API_KEY
              valueFrom:
                secretKeyRef:
                  key: GENIUS_API_KEY
                  name: spotifilter
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: spotifilter
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_TOKEN
                  name: spotifilter
          image: doronkg/spotifilter:latest
          imagePullPolicy: Always
