name: Deployment

on:
  push:
    branches:
      - kubernetes
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Set up Kubernetes config
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} > ~/.kube/config

      - name: Rollout Deployment
        run: kubectl rollout restart deployment spotifilter -n spotifilter
        env:
          KUBECONFIG: ~/.kube/config
